# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  name: Our Home
  latitude: 41.046709
  longitude: -95.9718365
  elevation: 1116
  time_zone: America/Chicago

# ðŸ‘‡ Use merge_named so each theme file can define its own theme name
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
scene: !include scenes.yaml
group: !include group.yaml
light: !include light.yaml
sensor: !include sensor.yaml
template: !include templates.yaml
binary_sensor: !include binary_sensors.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_text: !include input_text.yaml
script: !include scripts.yaml


lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
  dashboards:
    main-dashboard:
      mode: yaml
      filename: ui-lovelace/main.yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
      require_admin: false
    huskers-dashboard:
      mode: yaml
      filename: ui-lovelace/huskers.yaml
      title: Huskers
      icon: mdi:football-helmet
      show_in_sidebar: true
      require_admin: false
